import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect } from 'react';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Configuration, OpenAIApi } from 'openai';

let news = '';

useEffect(() => {
  const openai = new OpenAIApi(
    new Configuration({
      apiKey: process.env.API_KEY,
    })
  );

  openai
    .createChatCompletion({
      model: 'gpt-3.5-turbo',
      messages: [{ role: 'user', content: 'Tell me some positive news' }],
    })
    .then((res) => {
      console.log(res.data.choices[0].message.content);
      news = res.data.choices[0].message.content;
    })
    .catch((err) => {
      console.log(err.message);
    });
}, []);

// console.log(process.env.API_KEY);

if (typeof window !== 'undefined') {
  // browser code
  console.log(news);

  const accordian = document.querySelector('.accordian');

  accordian.addEventListener('click', (e) => {
    const activePanel = e.target.closest('.accordian-panel');
    if (!activePanel) return;
    toggleAccordian(activePanel);
  });

  function toggleAccordian(panelToActivate) {
    const buttons = panelToActivate.parentElement.querySelectorAll('button');

    const contents =
      panelToActivate.parentElement.querySelectorAll('.accordian-content');

    buttons.forEach((button) => {
      button.setAttribute('aria-expanded', false);
    });
    contents.forEach((content) => {
      content.setAttribute('aria-hidden', true);
    });

    panelToActivate.querySelector('button').setAttribute('aria-expanded', true);

    panelToActivate
      .querySelector('.accordian-content')
      .setAttribute('aria-hidden', false);
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>GoodNews</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='wrapper'>
        <h1>GOOD NEWS</h1>
        <div className='accordian'>
          <div className='accordian-panel'>
            <h2 id='panel1-heading'>
              <button
                className='accordian-trigger'
                aria-controls='panel1-content'
                aria-expanded='true'>
                <span className='accordian-title' id='panel1-title'>
                  Young Indian Activists
                </span>
                <svg aria-hidden='true' className='accordian-icon'>
                  {/* <use xlink:href='#news-svgrepo-com'></use> */}
                </svg>
              </button>
            </h2>
            <div
              className='accordian-content'
              id='panel1-content'
              aria-labelledby='panel1-heading'
              aria-hidden='false'
              role='region'>
              <p>{news}</p>
              <img
                className='accordian-image'
                src='https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y292aWR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60'
                alt='covid-19'
              />
            </div>
          </div>
          <div className='accordian-panel'>
            <h2 id='panel2-heading'>
              <button
                className='accordian-trigger'
                aria-controls='panel2-content'
                aria-expanded='false'>
                <span className='accordian-title' id='panel1-title'>
                  Biodegradable Plastic
                </span>
                <svg aria-hidden='true' className='accordian-icon'>
                  {/* <use xlink:href='#news-svgrepo-com'></use> */}
                </svg>
              </button>
            </h2>
            <div
              className='accordian-content'
              id='panel2-content'
              aria-labelledby='panel2-heading'
              aria-hidden='false'
              role='region'>
              <p>
                In the United States, a group of high school students in
                California have developed a biodegradable alternative to plastic
                wrap made from avocado pits. The product is not only
                eco-friendly, but also helps to reduce food waste by keeping
                produce fresher for longer.
              </p>
              <img
                className='accordian-image'
                src='https://images.unsplash.com/photo-1531326537431-6197cac3795b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8YmlvZGVncmFkYWJsZSUyMHBsYXN0aWN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60'
                alt='a camera'
              />
            </div>
          </div>
          <div className='accordian-panel'>
            <h2 id='panel3-heading'>
              <button
                className='accordian-trigger'
                aria-controls='panel1-content'
                aria-expanded='false'>
                <span className='accordian-title' id='panel3-title'>
                  Treatment for Alzheimer's
                </span>
                <svg aria-hidden='true' className='accordian-icon'>
                  {/* <use xlink:href='#news-svgrepo-com'></use> */}
                </svg>
              </button>
            </h2>
            <div
              className='accordian-content'
              id='panel3-content'
              aria-labelledby='panel3-heading'
              aria-hidden='false'
              role='region'>
              <p>
                A team of researchers at the University of California have
                developed a groundbreaking new treatment for Alzheimer's
                disease. The treatment involves using ultrasound to open up the
                blood-brain barrier and allow antibodies to enter the brain and
                clear out toxic proteins that cause Alzheimer's.
              </p>
              <img
                className='accordian-image'
                src='https://images.unsplash.com/photo-1565615833231-e8c91a38a012?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YWx6aGVpbWVyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60'
                alt='a gamepad'
              />
            </div>
          </div>
          <div className='accordian-panel'>
            <h2 id='panel4-heading'>
              <button
                className='accordian-trigger'
                aria-controls='panel4-content'
                aria-expanded='false'>
                <span className='accordian-title' id='panel4-title'>
                  Girls granted scholarships
                </span>
                <svg aria-hidden='true' className='accordian-icon'>
                  {/* <use xlink:href='#news-svgrepo-com'></use> */}
                </svg>
              </button>
            </h2>
            <div
              className='accordian-content'
              id='panel4-content'
              aria-labelledby='panel4-heading'
              aria-hidden='false'
              role='region'>
              <p>
                A group of Afghan girls who were forced to flee their country
                due to the Taliban's takeover have been granted scholarships to
                attend schools in the United States. The girls, who were part of
                an all-female robotics team in Afghanistan, will now have the
                opportunity to continue their education and pursue their dreams.
              </p>
              <img
                className='accordian-image'
                src='https://images.unsplash.com/photo-1464582883107-8adf2dca8a9f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGdpcmxzJTIwc3R1ZGVudHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60'
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
